export const cartActionTypes = {
  GET_USER_CART_REQUEST: "GET_USER_CART_REQUEST",
  GET_USER_CART_SUCCESS: "GET_USER_CART_SUCCESS",
  GET_USER_CART_FAIL: "GET_USER_CART_FAIL",
  GET_USER_CART_QUANTITY_REQUEST: "GET_USER_CART_QUANTITY_REQUEST",
  GET_USER_CART_QUANTITY_SUCCESS: "GET_USER_CART_QUANTITY_SUCCESS",
  GET_USER_CART_QUANTITY_FAIL: "GET_USER_CART_QUANTITY_FAIL",
};
