export const blogActionTypes = {
  //? Get ALl blogs
  ALL_BLOG_REQUEST: "ALL_BLOG_REQUEST",
  ALL_BLOG_SUCCESS: "ALL_BLOG_SUCCESS",
  ALL_BLOG_FAIL: "ALL_BLOG_FAIL",

  //? GET A SINGLE BLOG
  BLOG_REQUEST: "BLOG_REQUEST",
  BLOG_FAIL: "BLOG_FAIL",
  BLOG_SUCCESS: "BLOG_SUCCESS",

  //? CREATE BLOG  -- ADMIN
  CREATE_BLOG_REQUEST: "CREATE_BLOG_REQUEST",
  CREATE_BLOG_FAIL: "CREATE_BLOG_FAIL",
  CREATE_BLOG_SUCCESS: "CREATE_BLOG_SUCCESS",

  //? DELETE BLOG  -- ADMIN
  DELETE_BLOG_REQUEST: "DELETE_BLOG_REQUEST",
  DELETE_BLOG_FAIL: "DELETE_BLOG_FAIL",
  DELETE_BLOG_SUCCESS: "DELETE_BLOG_SUCCESS",

  //? UPDATE BLOG  -- ADMIN
  UPDATE_BLOG_REQUEST: "UPDATE_BLOG_REQUEST",
  UPDATE_BLOG_FAIL: "UPDATE_BLOG_FAIL",
  UPDATE_BLOG_SUCCESS: "UPDATE_BLOG_SUCCESS",
};
