export const categoryActionTypes = {
  //? GET ALL CATEGORY
  ALL_CATEGORY_REQUEST: "ALL_CATEGORY_REQUEST",
  ALL_CATEGORY_SUCCESS: "ALL_CATEGORY_SUCCESS",
  ALL_CATEGORY_FAIL: "ALL_CATEGORY_FAIL",
};
