export const bookActionTypes = {
  //? GET ALL BOOK
  ALL_BOOK_REQUEST: "ALL_BOOK_REQUEST",
  ALL_BOOK_SUCCESS: "ALL_BOOK_SUCCESS",
  ALL_BOOK_FAIL: "ALL_BOOK_FAIL",

  //? GET A SINGLE BOOK
  BOOK_REQUEST: "BOOK_REQUEST",
  BOOK_FAIL: "BOOK_FAIL",
  BOOK_SUCCESS: "BOOK_SUCCESS",

  //? GET top Feature BOOK
  TOP_BOOK_REQUEST: "TOP_BOOK_REQUEST",
  TOP_BOOK_FAIL: "TOP_BOOK_FAIL",
  TOP_BOOK_SUCCESS: "TOP_BOOK_SUCCESS",

  CATEGORY_BOOK_REQUEST: "CATEGORY_BOOK_REQUEST",
  CATEGORY_BOOK_SUCCESS: "CATEGORY_BOOK_SUCCESS",
  CATEGORY_BOOK_FAIL: "CATEGORY_BOOK_FAIL",


};
