export const orderActionTypes = {
  ALL_ORDER_REQUEST: "ALL_ORDER_REQUEST",
  ALL_ORDER_SUCCESS: "ALL_ORDER_SUCCESS",
  ALL_ORDER_FAIL: "ALL_ORDER_FAIL",
  SINGLE_ORDER_REQUEST: "SINGLE_ORDER_REQUEST",
  SINGLE_ORDER_SUCCESS: "SINGLE_ORDER_SUCCESS",
  SINGLE_ORDER_FAIL: "SINGLE_ORDER_FAIL",
};
