export const bookActionTypes = {
  ALL_BOOK_REQUEST: "ALL_BOOK_REQUEST",
  ALL_BOOK_SUCCESS: "ALL_BOOK_SUCCESS",
  ALL_BOOK_FAIL: "ALL_BOOK_FAIL",

  //? GET A SINGLE BOOK
  BOOK_REQUEST: "BOOK_REQUEST",
  BOOK_FAIL: "BOOK_FAIL",
  BOOK_SUCCESS: "BOOK_SUCCESS",

  //? CREATE BOOK  -- ADMIN
  CREATE_BOOK_REQUEST: "CREATE_BOOK_REQUEST",
  CREATE_BOOK_FAIL: "CREATE_BOOK_FAIL",
  CREATE_BOOK_SUCCESS: "CREATE_BOOK_SUCCESS",

  //? DELETE BOOK  -- ADMIN
  DELETE_BOOK_REQUEST: "DELETE_BOOK_REQUEST",
  DELETE_BOOK_FAIL: "DELETE_BOOK_FAIL",
  DELETE_BOOK_SUCCESS: "DELETE_BOOK_SUCCESS",

  //? UPDATE BOOK  -- ADMIN
  UPDATE_BOOK_REQUEST: "UPDATE_BOOK_REQUEST",
  UPDATE_BOOK_FAIL: "UPDATE_BOOK_FAIL",
  UPDATE_BOOK_SUCCESS: "UPDATE_BOOK_SUCCESS",
};
